### ISSUE TITLE
JLabel puntata minima non si aggiorna

### ISSUE THREAD

**Issue by giuseppe-steduto** [giuseppe-steduto/Poker#4]
La JLabel che mostra al giocatore la puntata minima si aggiorna solo se il giocatore che opera con quel client rilancia, ma rimane la stessa se un giocatore remoto rilancia (nonostante il meccanismo di puntata, e quindi il server, la aggiorni).

**Comment by MikeLeg01** [comment]
Problema risolto.
Ora si aggiorna.
Bug risolto. XD
