### ISSUE TITLE
Meccanismo di parola

### ISSUE THREAD

**Issue by giuseppe-steduto** [giuseppe-steduto/Poker#5]
Il client riesce a fare parola se un giocatore prima di lui punta una puntata uguale a quella minima. basta non rilanciare.
Non deve essere così, in quanto si dovrebbe poter fare parola solo se tutti i giocatori del turno precedente hanno fatto parola.

**Comment by giuseppe-steduto** [comment]
Fixing in progress. Il codice dovrebbe essere aggiustato ora, ma non posso dirlo finchè non lo proviamo su più computer in lab.
Pace e bene.

**Comment by MikeLeg01** [comment]
Ho appena provato io utilizzando due pc a casa e posso darti conferma del fatto che il meccanismo "fare parola" ora funziona.
Bug risolto. XD
